/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as ProductRouteImport } from './routes/product'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/business': typeof BusinessRoute
  '/experiences': typeof ExperiencesRoute
  '/flow': typeof FlowRoute
  '/matching': typeof MatchingRoute
  '/problem': typeof ProblemRoute
  '/product': typeof ProductRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/business': typeof BusinessRoute
  '/experiences': typeof ExperiencesRoute
  '/flow': typeof FlowRoute
  '/matching': typeof MatchingRoute
  '/problem': typeof ProblemRoute
  '/product': typeof ProductRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/business': typeof BusinessRoute
  '/experiences': typeof ExperiencesRoute
  '/flow': typeof FlowRoute
  '/matching': typeof MatchingRoute
  '/problem': typeof ProblemRoute
  '/product': typeof ProductRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/business'
    | '/experiences'
    | '/flow'
    | '/matching'
    | '/problem'
    | '/product'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/business'
    | '/experiences'
    | '/flow'
    | '/matching'
    | '/problem'
    | '/product'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/business'
    | '/experiences'
    | '/flow'
    | '/matching'
    | '/problem'
    | '/product'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BusinessRoute: typeof BusinessRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FlowRoute: typeof FlowRoute
  MatchingRoute: typeof MatchingRoute
  ProblemRoute: typeof ProblemRoute
  ProductRoute: typeof ProductRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BusinessRoute: BusinessRoute,
  ExperiencesRoute: ExperiencesRoute,
  FlowRoute: FlowRoute,
  MatchingRoute: MatchingRoute,
  ProblemRoute: ProblemRoute,
  ProductRoute: ProductRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
